base/urls.py
from django.urls import path
from . import views

app_name = 'base'
urlpatterns = [
    path('characters/', views.Characters, name='characters'),
    path('vehicles/', views.vehicles, name='vehicles'),
    path('game-modes/', views.gameModes, name='game-modes'),
    path('engine-classes/', views.engineClasses, name='engine-classes'),
    path('ctgp/', views.ctgp, name='ctgp'),
    path('wii/', views.wii, name='wii'),
    path('', views.index, name="index"),
]

mariokart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('user/', include('user.urls')),
    path('scraper/', include('scraper.urls')),
    path('tracktime/', include('timetracker.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scraper/urls.py
from django.urls import path

from . import views

app_name = 'scraper'
urlpatterns = [
    path('', views.index, name='index'),
    path('ctgp/', views.ctgp, name='ctgp'),
    path('wii/', views.wii, name='wii'),
    path('vehicles/', views.vehicles, name='vehicles'),
    path('characters/', views.characters, name='characters'),
    path('game-modes/', views.gameModes, name='game-modes'),
    path('engine-classes/', views.engineClasses, name='engine-classes'),

]

timetracker/urls.py
from django.urls import path
from . import views

app_name = 'timetracker'
urlpatterns = [
    path('wii/', views.wii, name='wii'),
    path('wii/record/', views.wiiRecord, name='wii-record'),
    path('', views.index, name="index"),
    path('ctgp/', views.index, name="index"),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('register/', views.registerUser, name='register'),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('', views.index, name="index"),
    path('profile/<str:pk>/', views.userProfile, name='profile'),
]

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="manifest" href="{% static 'manifest.webmanifest' %}">
  <link rel="shortcut icon" href="{% static 'images/icon/favicon-32x32-dunplab-manifest-18729.png' %}/">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500;700;900&display=swap" rel="stylesheet">
  <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/main.css' %}">
  {% block styles %}
  {% endblock styles %}
  <title>{% block title %}{% endblock title %} | Mario Kart Wii Companion</title>
</head>

<body class="background">
  <!-- <div id="loader">
    <div class="loader">Loading...</div>
  </div> -->
  {% include 'navbar.html' %}

  <button id="to-top" class="wii-button">☝</button>

  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags}}" {% endif %}>{{message}}</li>
      {% endfor %}
  </ul>
  {% endif %}

  {% block content %}
  {% endblock content %}

  {% block scripts %}
  {% endblock scripts %}
  <script src="{% static 'js/app.js' %}"></script>
</body>

</html>

templates/navbar.html
{% load static %}

<header id="banner">
  <div class="nav__main">

    <aside class="nav__mobile">
      <button class="nav__btn-toggle" data-mobile-menu-toggle>
        <svg viewBox="0 0 100 80" width="40" height="40">
          <rect width="100" height="16" rx="10"></rect>
          <rect y="30" width="100" height="16" rx="10"></rect>
          <rect y="60" width="100" height="16" rx="10"></rect>
        </svg>
      </button>

      <div class="offscreen-left nav__mobile-menu panel__translucent-dark" data-mobile-menu>
        <div class="nav__mobile-inner panel">
          <nav>
            <ul class="">
              {% if request.user.is_authenticated %}
              <li><a href="{% url 'timetracker:wii-record' %}" class="link scraper">Record Wii Time</a></li>
              {% endif %}
              <li><a href="{% url 'timetracker:index' %}" class="link scraper">Time Tracker</a></li>
              {% if request.user.is_superuser %}
              <li><a href="{% url 'scraper:index' %}" class="link scraper">Scraper</a></li>
              {% endif %}
              <li><a href="{% url 'base:characters' %}" class="link">characters</a></li>
              <li><a href="{% url 'base:vehicles' %}" class="link">vehicles</a></li>
              <li><a href="{% url 'base:game-modes' %}" class="link">game modes</a></li>
              <li><a href="{% url 'base:engine-classes' %}" class="link">engine classes</a></li>
              <li><a href="{% url 'base:wii' %}" class="link">Wii</a></li>
              <li><a href="{% url 'base:ctgp' %}" class="link">CTGP Revolution</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </aside>

    <a class="nav__logo" href="{% url 'base:index' %}">
      <picture>
        <source srcset="{%  static 'images/Mario_Kart_Wii_Logo-150w.png' %}" media="(max-width: 340px)">
        <source srcset="{%  static 'images/Mario_Kart_Wii_Logo-300w.png' %}" media="(max-width: 1080px)">
        <img src="{%  static 'images/Mario_Kart_Wii_Logo.png' %}" />
      </picture>
    </a>

    <!-- <form class="banner__search" method="GET" action="{% url 'base:index' %}">
    <input type="text" name="q" placeholder="Search Cups or Tracks..." />
  </form> -->

    <section class="nav__user">

      {% if request.user.is_authenticated %}
      <div class="nav__user-btn-group">
        <button data-menu-toggle>
          <div class="btn nav__user-toggle">
            {% if request.user.avatar %}
            <img class="nav__user-avatar" src="{% static 'images/characters/' %}{{request.user.avatar.image}}" />
            {% else %}
            <img class="nav__user-avatar" src="{% static 'images/characters/avatar.svg' %}" />
            {% endif %}
          </div>
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 32 32">
            <title>chevron-down</title>
            <path class="nav__user-chevron" d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
          </svg>
        </button>
      </div>

      <ul class="nav__user-menu veil panel border-blue" data-user-menu>
        <li><span>Signed is as</span> {{user.username}}</li>
        <li><a href="{% url 'user:profile' user.id %}">Profile</a></li>
        <li><a href="{% url 'user:logout' %}">Sign out</a></li>
      </ul>

      {% else %}
      <ul class="nav__user-auth">
        <li><a href="{% url 'user:login' %}">Sign In</a></li>
        <li><a href="{% url 'user:register' %}">Create Account</a></li>
      </ul>
      {% endif %}

    </section>
  </div>

</header>